apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | trim | indent 4 }}
{{- end }}
spec:
  backend:
    serviceName: {{ .Chart.Name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: andi.{{ .Values.ingress.rootDnsZone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
  - host: andi.{{ .Values.ingress.dnsZone }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: redirect
          servicePort: use-annotation
