name: Common Checks
on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.2.0
        with:
          elixir-version: 1.8
          otp-version: 22.2
          runs-on: ubuntu-latest
      - name: Run Static Checks
        run: |
          mix deps.get
          mix format --check-formatted
          mix credo
          mix sobelow
      - name: Run Unit Tests
        run: |
          mix test
      - name: Run E2E Tests
        run: |
          cd apps/e2e
          mix test.integration


